# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.twig_extension:
    class: AppBundle\Twig\AppExtension
    arguments:
      - @app.participation_service
    public: false
    tags:
      - { name: twig.extension }

  app.participation_service:
    class: AppBundle\Service\ParticipationService
    arguments:
      - @doctrine.orm.default_entity_manager
      - @security.token_storage
